### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by AndreLuna6** [SistemasTecTlaxiaco/infografia-AndreLuna6-1#1]
[Infografia1_AndreEmmanuelLunaGonzalez.pdf](https://github.com/SistemasTecTlaxiaco/infografia-AndreLuna6-1/files/8055104/Infografia1_AndreEmmanuelLunaGonzalez.pdf)

**Comment by javiern-778** [comment]
20% 
califico javer noe

**Comment by josealfredo79** [comment]
Esta bien hecho..revisado
